// Created by Rui MA on 02 Oct 2026

#pragma once

#define UNLOCK_PRODUCT_NAME "Unlock with iPhone\x00ae"
#define UNLOCK_WIDE_PRODUCT_IMPL(value) L##value
#define UNLOCK_WIDE_PRODUCT(value) UNLOCK_WIDE_PRODUCT_IMPL(value)
#define UNLOCK_PRODUCT_DISPLAY_NAME UNLOCK_WIDE_PRODUCT(UNLOCK_PRODUCT_NAME)

#define IDI_UNLOCK_APP 102
#define IDB_UNLOCK_TILE 103

#define IDD_PHONE_PAIRING 201
#define IDC_UI_TITLE 2001
#define IDC_UI_ACCOUNT 2002
#define IDC_UI_MESSAGE 2003
#define IDC_UI_FINGERPRINT 2004
#define IDC_UI_NOTICE 2005
