// Created by Rui MA on 02 Oct 2026

#pragma once

#define UNLOCK_PRODUCT_NAME "Unlock with iPhone\x00ae"
#define UNLOCK_WIDE_PRODUCT_IMPL(value) L##value
#define UNLOCK_WIDE_PRODUCT(value) UNLOCK_WIDE_PRODUCT_IMPL(value)
#define UNLOCK_PRODUCT_DISPLAY_NAME UNLOCK_WIDE_PRODUCT(UNLOCK_PRODUCT_NAME)

#define IDI_UNLOCK_APP 102
#define IDB_UNLOCK_TILE 103
